version: '3.8'

services:
  db:
    image: postgres:12.22
    container_name: mechatrack-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - mechatrack-data:/var/lib/postgresql/data
volumes:
  mechatrack-data:
